#!/usr/bin/env python
"""Generate sanitized local-machine instance notes."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess

SKILL_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = Path("~/.config/heaven-style/machine.md").expanduser()
REDACT_KEYS = (
    "Serial Number",
    "Hardware UUID",
    "Provisioning UDID",
    "Volume UUID",
    "Disk / Partition UUID",
    "APFS Snapshot UUID",
)


def run(args: tuple[str, ...] | list[str]) -> tuple[int, str]:
    """Return the exit code and successful stdout without exposing diagnostics."""
    try:
        result = subprocess.run(
            list(args),
            check=False,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        return 127, ""
    text = result.stdout.strip() if result.returncode == 0 else ""
    return result.returncode, text


def first_line(text: str) -> str:
    """Return the first non-empty output line."""
    return next((line.strip() for line in text.splitlines() if line.strip()), "")


def value(text: str, key: str) -> str:
    """Return a system_profiler or sw_vers field value."""
    match = re.search(rf"^\s*{re.escape(key)}:\s*(.+)$", text, re.M)
    return match.group(1).strip() if match else "unknown"


def clean_system_profiler(text: str) -> str:
    """Drop stable device identifiers from profiler output."""
    lines = []
    for line in text.splitlines():
        if any(key in line for key in REDACT_KEYS):
            continue
        lines.append(line)
    return "\n".join(lines)


def short_size(text: str) -> str:
    """Return a human-size field without byte-count detail."""
    return text.split(" (", 1)[0]


def command_path(name: str) -> str:
    """Return command path or a compact missing marker."""
    return shutil.which(name) or "not on PATH"


def build_markdown() -> str:
    """Return the machine note body."""
    _os_code, sw = run(("sw_vers",))
    _hw_code, hardware = run(("system_profiler", "SPHardwareDataType"))
    _disk_code, disk = run(("diskutil", "info", "/"))
    hardware = clean_system_profiler(hardware)
    disk = clean_system_profiler(disk)
    computer = first_line(run(("scutil", "--get", "ComputerName"))[1]) or "unknown"
    host = first_line(run(("scutil", "--get", "LocalHostName"))[1]) or "unknown"
    account = first_line(run(("whoami",))[1]) or "unknown"
    home = str(Path.home())
    shell = os.environ.get("SHELL") or "unknown"
    arch = first_line(run(("uname", "-m"))[1]) or "unknown"
    os_major = value(sw, "ProductVersion").split(".", 1)[0]
    brew_prefix = first_line(run(("brew", "--prefix"))[1]) or "unknown"
    docker_context = first_line(run(("docker", "context", "show"))[1]) or "unknown"
    setup = Path.home() / "Developer" / "Setup"
    setup_state = str(setup) if (setup / "docs" / "setup.md").is_file() else "not found; ask for the setup owner"
    _gpu_code, gpu = run(("system_profiler", "SPDisplaysDataType"))
    body = [
        "---",
        "name: asset-machine",
        "description: Read when checking the source machine’s hardware and tool observations.",
        "---",
        "",
        "# Local macOS Machine",
        "",
        "## Summary",
        "",
        "This snapshot records non-secret facts about the source machine. "
        "Verify relevant observations before using them on another machine or in a later session.",
        "",
        "## Snapshot scope",
        "",
        "Non-secret machine observations generated by `scripts/machine.py`.",
        "This snapshot describes the source machine only. Verify relevant facts before use.",
        "Volatile versions, free space, displays, live env values, and secret values are intentionally omitted.",
        "",
        "## Identity",
        "",
        f"- Computer: `{computer}`; local host: `{host}`.",
        f"- Account: `{account}`; home: `{home}`; configured shell: `{shell}`.",
        "- Standard skill install target: `~/.agents/skills/heaven-style`.",
        "",
        "## Platform",
        "",
        f"- macOS major `{os_major}` on `{arch}`.",
        f"- {value(hardware, 'Model Name')} `{value(hardware, 'Model Identifier')}`, {value(hardware, 'Chip')}.",
        f"- CPU: {value(hardware, 'Total Number of Cores')}; memory: {value(hardware, 'Memory')}; internal SSD: {short_size(value(disk, 'Disk Size'))}.",
        f"- GPU: {value(gpu, 'Total Number of Cores')} cores.",
        "",
        "## Observed tools and setup",
        "",
        f"- Homebrew prefix: `{brew_prefix}`.",
        f"- Docker context: `{docker_context}`. This does not prove daemon availability.",
        f"- Setup checkout: `{setup_state}`. Presence does not prove provisioning or profile binding.",
        "- Desired tool ownership belongs to the selected setup and repository metadata.",
        *[
            f"- `{name}`: `{command_path(name)}`."
            for name in (
                "python",
                "python3",
                "pip",
                "conda",
                "uv",
                "git",
                "gh",
                "bun",
                "pnpm",
                "node",
                "npm",
                "mise",
                "rustup",
                "docker",
                "code",
                "cursor",
            )
        ],
        "",
        "## Agent Notes",
        "",
        "- Prefer repository wrappers or the declared environment for project work. Use `uv run python` in uv-managed repositories.",
        "- Read the skill assets `MacOS-env.md` and `instance/setup.md` for setup ownership and missing-information recovery.",
        "- Run `gh auth status`, `docker context show`, or `docker info` only when those integrations fail.",
        "- Track this non-secret snapshot only after review. Never add secret values, tokens, serial numbers, UUIDs, private key paths, or transient state.",
        "",
    ]
    return "\n".join(body)


def main() -> int:
    """Write a non-secret machine report to the selected path."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Markdown output path")
    args = parser.parse_args()
    output = Path(args.output).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_markdown().rstrip("\n") + "\n", encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
