#!/usr/bin/env python
"""Generate sanitized local-machine instance notes."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess

SKILL_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = SKILL_ROOT / "assets" / "instance" / "machine.local.md"
REDACT_KEYS = (
    "Serial Number",
    "Hardware UUID",
    "Provisioning UDID",
    "Volume UUID",
    "Disk / Partition UUID",
    "APFS Snapshot UUID",
)


def run(args: tuple[str, ...] | list[str]) -> tuple[int, str]:
    """Return exit code and combined command text."""
    try:
        result = subprocess.run(list(args), check=False, capture_output=True, text=True, errors="replace")
    except FileNotFoundError:
        return 127, ""
    text = "\n".join(part for part in (result.stdout, result.stderr) if part).strip()
    return result.returncode, text


def first_line(text: str) -> str:
    """Return the first non-empty output line."""
    return next((line.strip() for line in text.splitlines() if line.strip()), "")


def value(text: str, key: str) -> str:
    """Return a system_profiler or sw_vers field value."""
    match = re.search(rf"^\s*{re.escape(key)}:\s*(.+)$", text, re.M)
    return match.group(1).strip() if match else "unknown"


def shell_value(script: str) -> str:
    """Return output from a small zsh probe."""
    return first_line(run(("zsh", "-lc", script))[1])


def clean_system_profiler(text: str) -> str:
    """Drop stable device identifiers from profiler output."""
    lines = []
    for line in text.splitlines():
        if any(key in line for key in REDACT_KEYS):
            continue
        lines.append(line)
    return "\n".join(lines)


def short_size(text: str) -> str:
    """Return a human-size field without byte-count detail."""
    return text.split(" (", 1)[0]


def command_path(name: str) -> str:
    """Return command path or a compact missing marker."""
    return shell_value(f"command -v {name} 2>/dev/null") or "not on PATH"


def miniforge_main_root(home: str) -> str:
    """Return the preferred global Miniforge main environment path."""
    conda_prefix = shell_value('printf %s "${CONDA_PREFIX:-}"')
    if "/miniforge3/envs/main" in conda_prefix:
        return conda_prefix
    conda_base = shell_value("conda info --base 2>/dev/null")
    if conda_base and conda_base != "unknown":
        return str(Path(conda_base) / "envs" / "main")
    conda_path = command_path("conda")
    if conda_path != "not on PATH" and "/condabin/conda" in conda_path:
        return str(Path(conda_path.split("/condabin/conda", 1)[0]) / "envs" / "main")
    return str(Path(home) / "miniforge3" / "envs" / "main")


def build_markdown() -> str:
    """Return the machine note body."""
    _os_code, sw = run(("sw_vers",))
    _hw_code, hardware = run(("system_profiler", "SPHardwareDataType"))
    _disk_code, disk = run(("diskutil", "info", "/"))
    hardware = clean_system_profiler(hardware)
    disk = clean_system_profiler(disk)
    computer = shell_value("scutil --get ComputerName")
    host = shell_value("scutil --get LocalHostName")
    account = shell_value("whoami")
    home = shell_value('printf %s "$HOME"')
    shell = shell_value('printf %s "$SHELL"')
    arch = first_line(run(("uname", "-m"))[1])
    os_major = value(sw, "ProductVersion").split(".", 1)[0]
    brew_prefix = first_line(run(("brew", "--prefix"))[1]) or "/opt/homebrew"
    docker_context = first_line(run(("docker", "context", "show"))[1]) or "desktop-linux"
    python_root = miniforge_main_root(home)
    body = [
        "# Local macOS Machine",
        "",
        "Durable local machine notes for Heaven-style agents. Generated by `scripts/machine.py`.",
        "Volatile versions, free space, displays, live env values, and secret values are intentionally omitted.",
        "",
        "## Identity",
        "",
        f"- Computer: `{computer}`; local host: `{host}`.",
        f"- Account: `{account}`; home: `{home}`; shell: `{shell}`.",
        "- Standard skill install target: `~/.agents/skills/heaven-style`.",
        "",
        "## Platform",
        "",
        f"- macOS major `{os_major}` on `{arch}`.",
        f"- {value(hardware, 'Model Name')} `{value(hardware, 'Model Identifier')}`, {value(hardware, 'Chip')}.",
        f"- CPU: {value(hardware, 'Total Number of Cores')}; memory: {value(hardware, 'Memory')}; internal SSD: {short_size(value(disk, 'Disk Size'))}.",
        "",
        "## Tool Ownership",
        "",
        f"- Homebrew: `{brew_prefix}` for native CLIs/apps; not the primary Python, Node, or Rust owner.",
        f"- Python/pip: global interactive Python uses Miniforge `main` at `{python_root}`.",
        "- uv: preferred project-level Python owner; repo wrappers and `uv run python` may shadow global `python` intentionally.",
        "- git/gh: Homebrew-owned CLI tools.",
        "- Bun/pnpm/Node/npm: Bun and pnpm are co-preferred for new TypeScript work; Node/npm use mise-owned shims under `~/.local/share/mise/shims`.",
        f"- Docker: Docker Desktop with context `{docker_context}`; daemon availability is runtime state.",
        "- Editors: VS Code and Cursor CLIs are installed.",
        "",
        "## Agent Notes",
        "",
        "- Prefer repo wrappers or `uv run python` for project work.",
        "- For macOS environment maintenance, read `assets/MacOS-env.md` before proposing host-tool, package-manager, or Docker update commands.",
        "- Run `gh auth status`, `docker context show`, or `docker info` only when those integrations fail.",
        "- Do not commit secret env values, tokens, serial numbers, UUIDs, local key paths, or transient machine state into this file.",
        "",
    ]
    return "\n".join(body)


def main() -> int:
    """CLI entrypoint."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Markdown output path")
    args = parser.parse_args()
    output = Path(args.output).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_markdown().rstrip("\n"), encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
