"""
Generate conda compatibility files and validate requirements sources.

Source of truth:
- requirements.txt
- requirements-dev.txt

pyproject.toml reads those files through setuptools dynamic metadata.
scripts/sync-env.bash then refreshes uv.lock, poetry.lock, and this conda adapter.

Tool priority for installs (highest to lowest):
1. uv        - uv.lock + `uv sync`
2. pip       - requirements*.txt + `pip install -e ".[dev]"`
3. pyproject - `pip install -e ".[dev]"` when only pyproject metadata is available
4. conda     - environment-dev.yml with `-e ".[dev]"`

Usage:
    python scripts/sync-env.py
    python scripts/sync-env.py --check
"""

from __future__ import annotations

import re
import sys

from heavenbase.utils import exists_file, get_file_dir, load_txt, pj, save_txt

ROOT = pj(get_file_dir(__file__), "..", abs=True)

_SOURCE_REQUIREMENTS = ("requirements.txt", "requirements-dev.txt")
_CONDA_FILE = "environment-dev.yml"
_CONDA_TEMPLATE = (
    "# Generated by scripts/sync-env.py - do not edit.\n"
    "# Edit requirements*.txt, then run bash scripts/sync-env.bash\n"
    "# Fallback: conda env create -f environment-dev.yml\n"
    "name: {name}-dev\n"
    "channels:\n"
    "  - conda-forge\n"
    "dependencies:\n"
    "  - python={python_ver}\n"
    "  - pip\n"
    "  - pip:\n"
    '    - -e ".[dev]"'
)


def _project_name(pyproject_text: str) -> str:
    match = re.search(r'^name = "([^"]+)"', pyproject_text, re.M)
    if not match:
        raise ValueError("missing [project].name in pyproject.toml")
    return match.group(1)


def _python_pin() -> str:
    path = pj(ROOT, ".python-version")
    if exists_file(path):
        return load_txt(path).strip()
    pyproject_text = load_txt(pj(ROOT, "pyproject.toml"))
    match = re.search(r'requires-python\s*=\s*"([^"]+)"', pyproject_text)
    return match.group(1) if match else "3.12"


def _package_version() -> str:
    version_py = pj(ROOT, "src", "blueprint", "version.py")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', load_txt(version_py))
    if not match:
        raise ValueError(f"missing __version__ in {version_py}")
    return match.group(1)


def _sync_poetry_version(pyproject_text: str) -> str:
    version = _package_version()
    lines: list[str] = []
    in_poetry = False
    for line in pyproject_text.splitlines():
        if line.strip() == "[tool.poetry]":
            in_poetry = True
        elif line.startswith("[") and in_poetry:
            in_poetry = False
        if in_poetry and line.startswith("version = "):
            line = f'version = "{version}"'
        lines.append(line)
    return "\n".join(lines) + "\n"


def _validate_pyproject_wiring(pyproject_text: str) -> None:
    if 'dynamic = ["version", "dependencies", "optional-dependencies"]' not in pyproject_text:
        raise SystemExit("pyproject.toml must declare dynamic version, dependencies, and optional-dependencies")
    if 'dependencies = { file = ["requirements.txt"] }' not in pyproject_text:
        raise SystemExit("pyproject.toml must load runtime deps from requirements.txt")
    if 'optional-dependencies.dev = { file = ["requirements-dev.txt"] }' not in pyproject_text:
        raise SystemExit("pyproject.toml must load dev extras from requirements-dev.txt")
    if re.search(r"^\s*dependencies\s*=\s*\[", pyproject_text, re.M):
        raise SystemExit("pyproject.toml must not inline [project].dependencies; edit requirements.txt")
    if re.search(r"^\s*\[project\.optional-dependencies\]", pyproject_text, re.M):
        raise SystemExit("pyproject.toml must not inline optional-dependencies; edit requirements-*.txt")


def _validate_requirements_sources() -> None:
    missing: list[str] = []
    empty: list[str] = []
    for filename in _SOURCE_REQUIREMENTS:
        path = pj(ROOT, filename)
        if not exists_file(path):
            missing.append(filename)
            continue
        lines = [line.strip() for line in load_txt(path).splitlines() if line.strip() and not line.strip().startswith("#")]
        if not lines:
            empty.append(filename)
    if missing:
        raise SystemExit(f"Missing requirements source file(s): {', '.join(missing)}")
    if empty:
        raise SystemExit(f"Requirements source file(s) have no dependency lines: {', '.join(empty)}")


def _expected_conda(pyproject_text: str) -> str:
    return (
        _CONDA_TEMPLATE.format(
            name=_project_name(pyproject_text),
            python_ver=_python_pin(),
        )
        + "\n"
    )


def generate(check: bool = False) -> None:
    pyproject_path = pj(ROOT, "pyproject.toml")
    pyproject_text = load_txt(pyproject_path)
    _validate_pyproject_wiring(pyproject_text)
    _validate_requirements_sources()
    synced_pyproject = _sync_poetry_version(pyproject_text)
    if not check and synced_pyproject != pyproject_text:
        save_txt(synced_pyproject.rstrip("\n"), pyproject_path)
        print("  synced [tool.poetry].version from src/blueprint/version.py")
        pyproject_text = synced_pyproject
    expected_conda = _expected_conda(pyproject_text)
    conda_path = pj(ROOT, _CONDA_FILE)

    if check:
        if not exists_file(conda_path) or load_txt(conda_path) != expected_conda:
            print(f"Compatibility file out of date: {_CONDA_FILE}", file=sys.stderr)
            print("Run: bash scripts/sync-env.bash", file=sys.stderr)
            sys.exit(1)
        print("Conda compatibility file is up to date.")
        return

    save_txt(expected_conda.rstrip("\n"), conda_path)
    print(f"  wrote {_CONDA_FILE}")
    print("[sync-env] conda compatibility file refreshed")


if __name__ == "__main__":
    generate(check="--check" in sys.argv)
